//! Imports a fixed Git ref snapshot into the cold store.
//!
//! The backend resolves refs once, walks immutable OIDs, and feeds raw object
//! payloads to the serialized cold-store writer. The source repository can be
//! removed after callers persist the returned snapshot metadata.

use std::{
    fs::{self, File, OpenOptions},
    io::{self, Read, Write},
    path::Path,
    process,
    time::{SystemTime, UNIX_EPOCH},
};

use reflink_forest_core::{ContentId, GitOid, HashAlgorithm};
use reflink_forest_format::{Codec, ObjectRecord};
use reflink_forest_git::{GitBackend, GitBackendError, LocalRefKind, RefSnapshot};
use reflink_forest_index::{Catalog, CatalogBatch, CatalogError, RepoId, SnapshotVisibility};
use reflink_forest_store::{ChunkWriter, StoreError};

/// The current binary encoding version for repository snapshot manifests.
pub const SNAPSHOT_MANIFEST_VERSION: u16 = 1;
/// Maximum accepted manifest size. This bounds parsing allocations for an
/// untrusted or partially written manifest.
pub const MAX_SNAPSHOT_MANIFEST_BYTES: usize = 16 * 1024 * 1024;
/// A repository snapshot ID is generated by the daemon rather than inferred
/// from mutable refs. It is deliberately distinct from a repository ID.
pub const REPO_SNAPSHOT_ID_LEN: usize = reflink_forest_index::SNAPSHOT_ID_LEN;

/// Import-layer name for the catalog's stable repository-snapshot ID.
///
/// Re-exporting the catalog type keeps durable manifest identity identical to
/// the ID used by visibility and GC-root records.
pub use reflink_forest_index::SnapshotId as RepoSnapshotId;

const SNAPSHOT_MANIFEST_MAGIC: &[u8; 8] = b"RFSNAP\0\0";
const MANIFEST_REF_NAME_MAX_BYTES: usize = 64 * 1024;
const MANIFEST_TOOL_VERSION_MAX_BYTES: usize = 64 * 1024;
const MANIFEST_OPTIONAL_FIELD_MAX_BYTES: usize = 4 * 1024 * 1024;
// A ref always carries its kind, name length, hash algorithm, OID length, and
// at least a SHA-1 OID.  These lower bounds let the decoder reject impossible
// count fields before reserving or iterating from untrusted input.
const MIN_MANIFEST_REF_ENTRY_BYTES: usize = 1 + 2 + 1 + 1 + 20;
const MIN_MANIFEST_OPTIONAL_FIELD_BYTES: usize = 2 + 4;

/// One byte-preserving local ref retained by a completed snapshot manifest.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PersistedRef {
    pub name: Vec<u8>,
    pub kind: LocalRefKind,
    pub target: GitOid,
}

/// Optional manifest data that this version does not otherwise interpret.
///
/// Unknown optional fields are retained verbatim on load and re-emitted on
/// write, so a v1 tool does not silently discard later optional metadata.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OptionalManifestField {
    pub tag: u16,
    pub value: Vec<u8>,
}

/// The exact ref-selection policy used for a snapshot import.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ImportPolicy {
    /// Import direct tips under `refs/heads/*` and `refs/tags/*` only.
    LocalBranchesAndTags,
}

/// A self-contained, durable description of a completed local-ref import.
///
/// This is deliberately separate from catalog publication. Callers write and
/// synchronize this manifest first, then make the corresponding snapshot
/// `Ready` in their catalog transaction. A manifest alone is never proof that
/// a snapshot is ready for user visibility.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SnapshotManifest {
    pub repository: RepoId,
    pub snapshot_id: RepoSnapshotId,
    pub native_object_format: HashAlgorithm,
    pub import_policy: ImportPolicy,
    pub refs: Vec<PersistedRef>,
    pub summary: ImportSummary,
    pub imported_unix_secs: u64,
    pub tool_version: Vec<u8>,
    pub optional_fields: Vec<OptionalManifestField>,
}

impl SnapshotManifest {
    /// Builds a manifest from a successfully imported immutable ref snapshot.
    pub fn from_import(
        repository: RepoId,
        snapshot_id: RepoSnapshotId,
        result: &ImportResult,
        imported_unix_secs: u64,
        tool_version: impl AsRef<[u8]>,
    ) -> Result<Self, SnapshotManifestError> {
        let manifest = Self {
            repository,
            snapshot_id,
            native_object_format: result.snapshot.algorithm,
            import_policy: ImportPolicy::LocalBranchesAndTags,
            refs: result
                .snapshot
                .refs
                .iter()
                .map(|reference| PersistedRef {
                    name: reference.name.as_bytes().to_vec(),
                    kind: reference.kind,
                    target: reference.target,
                })
                .collect(),
            summary: result.summary,
            imported_unix_secs,
            tool_version: tool_version.as_ref().to_vec(),
            optional_fields: Vec::new(),
        };
        manifest.validate()?;
        Ok(manifest)
    }

    /// Adds opaque optional data. Duplicate tags are rejected because a
    /// future reader could otherwise give an ambiguous meaning to a field.
    pub fn add_optional_field(
        &mut self,
        field: OptionalManifestField,
    ) -> Result<(), SnapshotManifestError> {
        if self
            .optional_fields
            .iter()
            .any(|existing| existing.tag == field.tag)
        {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest repeats an optional field tag",
            ));
        }
        if field.tag == 0 {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest optional field tag is zero",
            ));
        }
        if field.value.len() > MANIFEST_OPTIONAL_FIELD_MAX_BYTES {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest optional field is too large",
            ));
        }
        self.optional_fields.push(field);
        Ok(())
    }

    /// Fully validates this in-memory manifest before it can become a GC
    /// root.  This is public because callers that receive a manifest through
    /// an abstraction other than [`read_snapshot_manifest`] must not trust
    /// mutable public fields without re-validating them.
    pub fn validate(&self) -> Result<(), SnapshotManifestError> {
        if self.tool_version.is_empty() || self.tool_version.len() > MANIFEST_TOOL_VERSION_MAX_BYTES
        {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest tool version is empty or too large",
            ));
        }
        if self
            .summary
            .objects_written
            .checked_add(self.summary.objects_deduplicated)
            != Some(self.summary.objects_seen)
        {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest import counters are inconsistent",
            ));
        }
        if self.refs.len() > u32::MAX as usize {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest has too many refs",
            ));
        }
        let mut previous_name = None;
        for reference in &self.refs {
            if reference.name.is_empty() || reference.name.len() > MANIFEST_REF_NAME_MAX_BYTES {
                return Err(SnapshotManifestError::Invalid(
                    "snapshot manifest ref name is empty or too large",
                ));
            }
            if reference.target.algorithm() != self.native_object_format {
                return Err(SnapshotManifestError::Invalid(
                    "snapshot manifest ref OID algorithm disagrees with native object format",
                ));
            }
            let namespace = match reference.kind {
                LocalRefKind::Branch => b"refs/heads/".as_slice(),
                LocalRefKind::Tag => b"refs/tags/".as_slice(),
            };
            if !reference.name.starts_with(namespace) {
                return Err(SnapshotManifestError::Invalid(
                    "snapshot manifest ref is outside its local namespace",
                ));
            }
            if let Some(previous_name) = previous_name {
                if previous_name >= reference.name.as_slice() {
                    return Err(SnapshotManifestError::Invalid(
                        "snapshot manifest refs are not strictly byte sorted",
                    ));
                }
            }
            previous_name = Some(reference.name.as_slice());
        }
        if self.optional_fields.len() > u32::MAX as usize {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest has too many optional fields",
            ));
        }
        for (index, field) in self.optional_fields.iter().enumerate() {
            if field.tag == 0 || field.value.len() > MANIFEST_OPTIONAL_FIELD_MAX_BYTES {
                return Err(SnapshotManifestError::Invalid(
                    "snapshot manifest contains an invalid optional field",
                ));
            }
            if self.optional_fields[..index]
                .iter()
                .any(|prior| prior.tag == field.tag)
            {
                return Err(SnapshotManifestError::Invalid(
                    "snapshot manifest repeats an optional field tag",
                ));
            }
        }
        Ok(())
    }
}

/// Failure while encoding, publishing, or loading a snapshot manifest.
#[derive(Debug)]
pub enum SnapshotManifestError {
    Io(io::Error),
    Invalid(&'static str),
    UnsupportedVersion(u16),
    LengthOverflow,
}

impl std::fmt::Display for SnapshotManifestError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(error) => write!(f, "snapshot manifest I/O error: {error}"),
            Self::Invalid(reason) => write!(f, "invalid snapshot manifest: {reason}"),
            Self::UnsupportedVersion(version) => {
                write!(f, "unsupported snapshot manifest version {version}")
            }
            Self::LengthOverflow => write!(f, "snapshot manifest length overflow"),
        }
    }
}
impl std::error::Error for SnapshotManifestError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(error) => Some(error),
            _ => None,
        }
    }
}
impl From<io::Error> for SnapshotManifestError {
    fn from(value: io::Error) -> Self {
        Self::Io(value)
    }
}

/// Result of finishing a repository snapshot's visibility publication.
///
/// `AlreadyReady` is useful to recovery code: it proves that the durable
/// manifest passed validation and that a previous process had already made
/// this snapshot visible.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SnapshotPublicationStatus {
    Published,
    AlreadyReady,
}

/// Failure while moving a durable snapshot manifest through catalog
/// visibility.
///
/// The only transition to `Ready` is performed after the manifest was written
/// and re-read successfully. A catalog failure therefore leaves either no
/// record or an `Incomplete` record, neither of which is a GC root.
#[derive(Debug)]
pub enum SnapshotPublicationError {
    Manifest(SnapshotManifestError),
    Catalog(CatalogError),
    SnapshotAlreadyReady,
    SnapshotNotMarkedIncomplete,
    PersistedManifestMismatch,
}
impl std::fmt::Display for SnapshotPublicationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Manifest(error) => write!(f, "snapshot manifest publication failed: {error}"),
            Self::Catalog(error) => write!(f, "snapshot catalog publication failed: {error:?}"),
            Self::SnapshotAlreadyReady => {
                write!(f, "repository snapshot is already visible as Ready")
            }
            Self::SnapshotNotMarkedIncomplete => write!(
                f,
                "repository snapshot has no Incomplete catalog publication marker"
            ),
            Self::PersistedManifestMismatch => write!(
                f,
                "persisted snapshot manifest does not match the manifest being published"
            ),
        }
    }
}
impl std::error::Error for SnapshotPublicationError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Manifest(error) => Some(error),
            _ => None,
        }
    }
}
impl From<SnapshotManifestError> for SnapshotPublicationError {
    fn from(value: SnapshotManifestError) -> Self {
        Self::Manifest(value)
    }
}

/// Records a snapshot publication as incomplete before its external manifest
/// is made visible.
///
/// This intentionally refuses to overwrite `Ready`: snapshot IDs are
/// immutable publication identities, and demoting a ready snapshot after a
/// caller accidentally reuses an ID could make live cold data collectable.
/// Retrying an existing `Incomplete` publication is safe.
pub fn begin_snapshot_publication<C: Catalog>(
    catalog: &mut C,
    manifest: &SnapshotManifest,
) -> Result<(), SnapshotPublicationError> {
    manifest.validate()?;
    match catalog.repository_snapshot(manifest.repository, manifest.snapshot_id) {
        Some(SnapshotVisibility::Ready) => Err(SnapshotPublicationError::SnapshotAlreadyReady),
        Some(SnapshotVisibility::Incomplete) => Ok(()),
        None => {
            let mut batch = CatalogBatch::new();
            batch.put_repository_snapshot(
                manifest.repository,
                manifest.snapshot_id,
                SnapshotVisibility::Incomplete,
            );
            catalog
                .apply(batch)
                .map_err(SnapshotPublicationError::Catalog)
        }
    }
}

/// Publishes a repository snapshot only after its manifest is durable.
///
/// The transaction has three crash-safe stages:
///
/// 1. record `Incomplete` in the catalog;
/// 2. create, synchronize, rename, and directory-synchronize the manifest;
/// 3. atomically replace the catalog visibility with `Ready`.
///
/// A crash or catalog failure in stages 1–2 cannot expose a `Ready` snapshot.
/// A crash after stage 2 leaves an `Incomplete` marker that
/// [`reconcile_snapshot_publication`] can safely finish after validating the
/// on-disk manifest.
pub fn publish_snapshot_manifest<C: Catalog>(
    catalog: &mut C,
    path: impl AsRef<Path>,
    manifest: &SnapshotManifest,
) -> Result<SnapshotPublicationStatus, SnapshotPublicationError> {
    begin_snapshot_publication(catalog, manifest)?;
    write_snapshot_manifest(path.as_ref(), manifest)?;
    finish_snapshot_publication(catalog, path, manifest)
}

/// Finishes an incomplete publication after proving that the exact requested
/// manifest is already durable at `path`.
///
/// This is deliberately exposed for a daemon that writes the manifest before
/// it is interrupted. It cannot promote a snapshot with a missing, malformed,
/// or mismatched manifest.
pub fn finish_snapshot_publication<C: Catalog>(
    catalog: &mut C,
    path: impl AsRef<Path>,
    expected: &SnapshotManifest,
) -> Result<SnapshotPublicationStatus, SnapshotPublicationError> {
    let persisted = read_snapshot_manifest(path)?;
    if &persisted != expected {
        return Err(SnapshotPublicationError::PersistedManifestMismatch);
    }
    finish_persisted_snapshot_publication(catalog, &persisted)
}

/// Reconciles an interrupted manifest publication.
///
/// Only a matching `Incomplete` marker may be promoted. A manifest with no
/// marker remains invisible: this avoids resurrecting a snapshot manifest that
/// was left behind after repository deletion.
pub fn reconcile_snapshot_publication<C: Catalog>(
    catalog: &mut C,
    path: impl AsRef<Path>,
) -> Result<SnapshotPublicationStatus, SnapshotPublicationError> {
    let manifest = read_snapshot_manifest(path)?;
    finish_persisted_snapshot_publication(catalog, &manifest)
}

fn finish_persisted_snapshot_publication<C: Catalog>(
    catalog: &mut C,
    manifest: &SnapshotManifest,
) -> Result<SnapshotPublicationStatus, SnapshotPublicationError> {
    match catalog.repository_snapshot(manifest.repository, manifest.snapshot_id) {
        Some(SnapshotVisibility::Ready) => Ok(SnapshotPublicationStatus::AlreadyReady),
        Some(SnapshotVisibility::Incomplete) => {
            let mut batch = CatalogBatch::new();
            batch.put_repository_snapshot(
                manifest.repository,
                manifest.snapshot_id,
                SnapshotVisibility::Ready,
            );
            catalog
                .apply(batch)
                .map_err(SnapshotPublicationError::Catalog)?;
            Ok(SnapshotPublicationStatus::Published)
        }
        None => Err(SnapshotPublicationError::SnapshotNotMarkedIncomplete),
    }
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ImportSummary {
    pub objects_seen: u64,
    pub objects_written: u64,
    pub objects_deduplicated: u64,
    pub raw_bytes: u64,
}
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ImportResult {
    pub snapshot: RefSnapshot,
    pub summary: ImportSummary,
}
#[derive(Debug)]
pub enum ImportError {
    Git(GitBackendError),
    Store(StoreError),
    LengthOverflow,
}
impl std::fmt::Display for ImportError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Git(error) => write!(f, "Git import error: {error}"),
            Self::Store(error) => write!(f, "cold-store import error: {error}"),
            Self::LengthOverflow => write!(f, "import counter overflow"),
        }
    }
}
impl std::error::Error for ImportError {}
impl From<GitBackendError> for ImportError {
    fn from(value: GitBackendError) -> Self {
        Self::Git(value)
    }
}
impl From<StoreError> for ImportError {
    fn from(value: StoreError) -> Self {
        Self::Store(value)
    }
}

/// Writes a complete repository snapshot manifest using the durable
/// temporary-file, sync, rename, and parent-directory-sync sequence.
///
/// Replacing an existing manifest is atomic. A failed write never makes the
/// temporary file a visible manifest, although the old manifest remains until
/// the rename succeeds.
pub fn write_snapshot_manifest(
    path: impl AsRef<Path>,
    manifest: &SnapshotManifest,
) -> Result<(), SnapshotManifestError> {
    manifest.validate()?;
    let bytes = encode_snapshot_manifest(manifest)?;
    let path = path.as_ref();
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    let (temporary, mut file) = create_manifest_temporary_file(parent)?;
    let result = (|| -> Result<(), SnapshotManifestError> {
        file.write_all(&bytes)?;
        file.sync_all()?;
        drop(file);
        fs::rename(&temporary, path)?;
        File::open(parent)?.sync_all()?;
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result
}

/// Reads and fully validates a repository snapshot manifest. Unknown optional
/// fields remain in [`SnapshotManifest::optional_fields`] so callers can
/// retain them on a later rewrite.
pub fn read_snapshot_manifest(
    path: impl AsRef<Path>,
) -> Result<SnapshotManifest, SnapshotManifestError> {
    let mut file = File::open(path)?;
    let length = usize::try_from(file.metadata()?.len())
        .map_err(|_| SnapshotManifestError::LengthOverflow)?;
    if length > MAX_SNAPSHOT_MANIFEST_BYTES {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest exceeds the maximum size",
        ));
    }
    let mut bytes = Vec::with_capacity(length);
    file.read_to_end(&mut bytes)?;
    if bytes.len() != length {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest changed while being read",
        ));
    }
    decode_snapshot_manifest(&bytes)
}

fn encode_snapshot_manifest(manifest: &SnapshotManifest) -> Result<Vec<u8>, SnapshotManifestError> {
    manifest.validate()?;
    let mut bytes = Vec::new();
    bytes.extend_from_slice(SNAPSHOT_MANIFEST_MAGIC);
    put_u16(&mut bytes, SNAPSHOT_MANIFEST_VERSION);
    bytes.extend_from_slice(&manifest.repository.0);
    bytes.extend_from_slice(&manifest.snapshot_id.0);
    bytes.push(manifest.native_object_format.tag());
    bytes.push(import_policy_tag(manifest.import_policy));
    put_u16(&mut bytes, 0); // required reserved bytes
    put_u64(&mut bytes, manifest.imported_unix_secs);
    put_u64(&mut bytes, manifest.summary.objects_seen);
    put_u64(&mut bytes, manifest.summary.objects_written);
    put_u64(&mut bytes, manifest.summary.objects_deduplicated);
    put_u64(&mut bytes, manifest.summary.raw_bytes);
    put_u16(
        &mut bytes,
        u16::try_from(manifest.tool_version.len())
            .map_err(|_| SnapshotManifestError::LengthOverflow)?,
    );
    put_u32(
        &mut bytes,
        u32::try_from(manifest.refs.len()).map_err(|_| SnapshotManifestError::LengthOverflow)?,
    );
    put_u32(
        &mut bytes,
        u32::try_from(manifest.optional_fields.len())
            .map_err(|_| SnapshotManifestError::LengthOverflow)?,
    );
    bytes.extend_from_slice(&manifest.tool_version);
    for reference in &manifest.refs {
        bytes.push(local_ref_kind_tag(reference.kind));
        put_u16(
            &mut bytes,
            u16::try_from(reference.name.len())
                .map_err(|_| SnapshotManifestError::LengthOverflow)?,
        );
        bytes.extend_from_slice(&reference.name);
        bytes.push(reference.target.algorithm().tag());
        bytes.push(reference.target.len());
        bytes.extend_from_slice(reference.target.as_bytes());
    }
    for field in &manifest.optional_fields {
        put_u16(&mut bytes, field.tag);
        put_u32(
            &mut bytes,
            u32::try_from(field.value.len()).map_err(|_| SnapshotManifestError::LengthOverflow)?,
        );
        bytes.extend_from_slice(&field.value);
    }
    if bytes.len() > MAX_SNAPSHOT_MANIFEST_BYTES {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest exceeds the maximum size",
        ));
    }
    Ok(bytes)
}

fn decode_snapshot_manifest(bytes: &[u8]) -> Result<SnapshotManifest, SnapshotManifestError> {
    if bytes.len() > MAX_SNAPSHOT_MANIFEST_BYTES {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest exceeds the maximum size",
        ));
    }
    let mut reader = ManifestReader::new(bytes);
    if reader.take(8)? != SNAPSHOT_MANIFEST_MAGIC {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest has an invalid magic value",
        ));
    }
    let version = reader.u16()?;
    if version != SNAPSHOT_MANIFEST_VERSION {
        return Err(SnapshotManifestError::UnsupportedVersion(version));
    }
    let repository = RepoId(reader.array::<16>()?);
    let snapshot_id = RepoSnapshotId(reader.array::<REPO_SNAPSHOT_ID_LEN>()?);
    let native_object_format = HashAlgorithm::from_tag(reader.u8()?).ok_or(
        SnapshotManifestError::Invalid("snapshot manifest has an invalid native object format"),
    )?;
    let import_policy = import_policy_from_tag(reader.u8()?)?;
    if reader.u16()? != 0 {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest has non-zero required reserved bytes",
        ));
    }
    let imported_unix_secs = reader.u64()?;
    let summary = ImportSummary {
        objects_seen: reader.u64()?,
        objects_written: reader.u64()?,
        objects_deduplicated: reader.u64()?,
        raw_bytes: reader.u64()?,
    };
    let tool_version_length = usize::from(reader.u16()?);
    if tool_version_length > MANIFEST_TOOL_VERSION_MAX_BYTES {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest tool version is too large",
        ));
    }
    let ref_count =
        usize::try_from(reader.u32()?).map_err(|_| SnapshotManifestError::LengthOverflow)?;
    let optional_field_count =
        usize::try_from(reader.u32()?).map_err(|_| SnapshotManifestError::LengthOverflow)?;
    let tool_version = reader.take(tool_version_length)?.to_vec();
    if ref_count > reader.remaining() / MIN_MANIFEST_REF_ENTRY_BYTES {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest ref count exceeds remaining input",
        ));
    }
    let mut refs = Vec::with_capacity(ref_count.min(4096));
    for _ in 0..ref_count {
        let kind = local_ref_kind_from_tag(reader.u8()?)?;
        let name_length = usize::from(reader.u16()?);
        if name_length > MANIFEST_REF_NAME_MAX_BYTES {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest ref name is too large",
            ));
        }
        let name = reader.take(name_length)?.to_vec();
        let algorithm = HashAlgorithm::from_tag(reader.u8()?).ok_or(
            SnapshotManifestError::Invalid("snapshot manifest has an invalid ref OID algorithm"),
        )?;
        let oid_length = reader.u8()?;
        if oid_length != algorithm.oid_len() {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest has an invalid ref OID length",
            ));
        }
        let target =
            GitOid::new(algorithm, reader.take(usize::from(oid_length))?).map_err(|_| {
                SnapshotManifestError::Invalid("snapshot manifest has an invalid ref OID")
            })?;
        refs.push(PersistedRef { name, kind, target });
    }
    if optional_field_count > reader.remaining() / MIN_MANIFEST_OPTIONAL_FIELD_BYTES {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest optional field count exceeds remaining input",
        ));
    }
    let mut optional_fields = Vec::with_capacity(optional_field_count.min(64));
    for _ in 0..optional_field_count {
        let tag = reader.u16()?;
        let length =
            usize::try_from(reader.u32()?).map_err(|_| SnapshotManifestError::LengthOverflow)?;
        if length > MANIFEST_OPTIONAL_FIELD_MAX_BYTES {
            return Err(SnapshotManifestError::Invalid(
                "snapshot manifest optional field is too large",
            ));
        }
        optional_fields.push(OptionalManifestField {
            tag,
            value: reader.take(length)?.to_vec(),
        });
    }
    if !reader.is_empty() {
        return Err(SnapshotManifestError::Invalid(
            "snapshot manifest has trailing bytes",
        ));
    }
    let manifest = SnapshotManifest {
        repository,
        snapshot_id,
        native_object_format,
        import_policy,
        refs,
        summary,
        imported_unix_secs,
        tool_version,
        optional_fields,
    };
    manifest.validate()?;
    Ok(manifest)
}

fn create_manifest_temporary_file(
    parent: &Path,
) -> Result<(std::path::PathBuf, File), SnapshotManifestError> {
    for attempt in 0..32_u32 {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_err(|_| SnapshotManifestError::Invalid("system clock is before the Unix epoch"))?
            .as_nanos();
        let temporary = parent.join(format!(
            ".reflink-forest-snapshot-{}-{timestamp}-{attempt}",
            process::id()
        ));
        match OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)
        {
            Ok(file) => return Ok((temporary, file)),
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(SnapshotManifestError::Io(error)),
        }
    }
    Err(SnapshotManifestError::Invalid(
        "cannot allocate a temporary snapshot manifest path",
    ))
}

fn import_policy_tag(policy: ImportPolicy) -> u8 {
    match policy {
        ImportPolicy::LocalBranchesAndTags => 1,
    }
}

fn import_policy_from_tag(tag: u8) -> Result<ImportPolicy, SnapshotManifestError> {
    match tag {
        1 => Ok(ImportPolicy::LocalBranchesAndTags),
        _ => Err(SnapshotManifestError::Invalid(
            "snapshot manifest has an unsupported import policy",
        )),
    }
}

fn local_ref_kind_tag(kind: LocalRefKind) -> u8 {
    match kind {
        LocalRefKind::Branch => 1,
        LocalRefKind::Tag => 2,
    }
}

fn local_ref_kind_from_tag(tag: u8) -> Result<LocalRefKind, SnapshotManifestError> {
    match tag {
        1 => Ok(LocalRefKind::Branch),
        2 => Ok(LocalRefKind::Tag),
        _ => Err(SnapshotManifestError::Invalid(
            "snapshot manifest has an invalid ref kind",
        )),
    }
}

fn put_u16(bytes: &mut Vec<u8>, value: u16) {
    bytes.extend_from_slice(&value.to_be_bytes());
}
fn put_u32(bytes: &mut Vec<u8>, value: u32) {
    bytes.extend_from_slice(&value.to_be_bytes());
}
fn put_u64(bytes: &mut Vec<u8>, value: u64) {
    bytes.extend_from_slice(&value.to_be_bytes());
}

struct ManifestReader<'a> {
    bytes: &'a [u8],
    offset: usize,
}
impl<'a> ManifestReader<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, offset: 0 }
    }
    fn take(&mut self, length: usize) -> Result<&'a [u8], SnapshotManifestError> {
        let end = self
            .offset
            .checked_add(length)
            .ok_or(SnapshotManifestError::LengthOverflow)?;
        let value = self
            .bytes
            .get(self.offset..end)
            .ok_or(SnapshotManifestError::Invalid(
                "snapshot manifest is truncated",
            ))?;
        self.offset = end;
        Ok(value)
    }
    fn array<const N: usize>(&mut self) -> Result<[u8; N], SnapshotManifestError> {
        self.take(N)?.try_into().map_err(|_| {
            SnapshotManifestError::Invalid("snapshot manifest fixed field is truncated")
        })
    }
    fn u8(&mut self) -> Result<u8, SnapshotManifestError> {
        Ok(self.take(1)?[0])
    }
    fn u16(&mut self) -> Result<u16, SnapshotManifestError> {
        Ok(u16::from_be_bytes(self.array()?))
    }
    fn u32(&mut self) -> Result<u32, SnapshotManifestError> {
        Ok(u32::from_be_bytes(self.array()?))
    }
    fn u64(&mut self) -> Result<u64, SnapshotManifestError> {
        Ok(u64::from_be_bytes(self.array()?))
    }
    fn is_empty(&self) -> bool {
        self.offset == self.bytes.len()
    }
    fn remaining(&self) -> usize {
        self.bytes.len() - self.offset
    }
}

/// Imports local branch/tag closure. Publication of a repository `Ready`
/// snapshot is deliberately a separate durable manifest transaction after this
/// function completes without error.
pub fn import_local_refs<B: GitBackend, C: Catalog>(
    backend: &B,
    writer: &mut ChunkWriter,
    catalog: &mut C,
    repo: RepoId,
    generation: u32,
    chunk_id: u64,
) -> Result<ImportResult, ImportError> {
    let snapshot = backend.snapshot_local_refs()?;
    let objects = backend.reachable_objects(&snapshot.roots())?;
    let mut summary = ImportSummary::default();
    for object in objects {
        summary.objects_seen = summary
            .objects_seen
            .checked_add(1)
            .ok_or(ImportError::LengthOverflow)?;
        summary.raw_bytes = summary
            .raw_bytes
            .checked_add(u64::try_from(object.data.len()).map_err(|_| ImportError::LengthOverflow)?)
            .ok_or(ImportError::LengthOverflow)?;
        let content_id = ContentId::for_object(object.kind, &object.data);
        let record = ObjectRecord {
            kind: object.kind,
            codec: Codec::Raw,
            flags: 0,
            raw_length: u64::try_from(object.data.len())
                .map_err(|_| ImportError::LengthOverflow)?,
            content_id,
            primary_oid: object.oid,
            payload: object.data,
        };
        if writer
            .append_and_index(catalog, repo, generation, chunk_id, &record)?
            .is_some()
        {
            summary.objects_written = summary
                .objects_written
                .checked_add(1)
                .ok_or(ImportError::LengthOverflow)?;
        } else {
            summary.objects_deduplicated = summary
                .objects_deduplicated
                .checked_add(1)
                .ok_or(ImportError::LengthOverflow)?;
        }
    }
    Ok(ImportResult { snapshot, summary })
}

#[cfg(test)]
mod tests {
    use super::*;
    use reflink_forest_core::ObjectKind;
    use reflink_forest_format::{decode_record, ChunkHeader};
    use reflink_forest_git::{GitObject, SystemGitBackend};
    use reflink_forest_index::{Catalog, InMemoryCatalog};
    use reflink_forest_store::verify_chunk;
    use std::{
        ffi::OsStr,
        fs,
        path::{Path, PathBuf},
        process::Command,
        sync::atomic::{AtomicU64, Ordering},
        time::{SystemTime, UNIX_EPOCH},
    };

    static NEXT_TEMPORARY_ID: AtomicU64 = AtomicU64::new(0);

    fn temporary_directory(label: &str) -> PathBuf {
        let unique = NEXT_TEMPORARY_ID.fetch_add(1, Ordering::Relaxed);
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock after Unix epoch")
            .as_nanos();
        let directory = std::env::temp_dir().join(format!(
            "reflink-forest-import-{label}-{}-{nanos}-{unique}",
            process::id()
        ));
        fs::create_dir(&directory).expect("create temporary test directory");
        directory
    }

    fn run_git<I, S>(repository: &Path, args: I)
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
    {
        let output = Command::new("git")
            .current_dir(repository)
            .args(args)
            .output()
            .expect("run test git command");
        assert!(
            output.status.success(),
            "test git command failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    fn create_repository(root: &Path) -> PathBuf {
        let repository = root.join("source");
        fs::create_dir(&repository).expect("create source repository");
        run_git(&repository, ["init", "-b", "main"]);
        run_git(&repository, ["config", "user.name", "Import Test"]);
        run_git(
            &repository,
            ["config", "user.email", "import-test@example.invalid"],
        );
        fs::create_dir(repository.join("directory")).expect("create nested directory");
        fs::write(repository.join("top.txt"), b"top-level blob\n").expect("write top blob");
        fs::write(repository.join("directory/nested.txt"), b"nested blob\n")
            .expect("write nested blob");
        run_git(&repository, ["add", "."]);
        run_git(&repository, ["commit", "-m", "initial import fixture"]);
        run_git(
            &repository,
            ["tag", "-a", "v1", "-m", "annotated import fixture"],
        );
        repository
    }

    fn record_for_oid(
        chunk: &Path,
        catalog: &InMemoryCatalog,
        repository: RepoId,
        oid: GitOid,
    ) -> ObjectRecord {
        let content_id = catalog
            .oid_alias(repository, &oid)
            .expect("imported OID alias remains available");
        let location = catalog
            .object_location(content_id)
            .expect("imported object location remains available");
        let bytes = fs::read(chunk).expect("read imported chunk");
        let offset = usize::try_from(location.offset).expect("test offset fits usize");
        let record_length =
            usize::try_from(location.record_length).expect("test length fits usize");
        let end = offset
            .checked_add(record_length)
            .expect("test record range fits");
        let (record, consumed) = decode_record(&bytes[offset..end]).expect("decode stored record");
        assert_eq!(consumed, record_length);
        assert_eq!(record.content_id, content_id);
        assert_eq!(record.primary_oid, oid);
        record
    }

    fn oid_from_hex(algorithm: HashAlgorithm, value: &[u8]) -> GitOid {
        assert_eq!(value.len(), usize::from(algorithm.oid_len()) * 2);
        let mut bytes = [0_u8; 32];
        for (index, pair) in value.chunks_exact(2).enumerate() {
            bytes[index] = (hex_digit(pair[0]) << 4) | hex_digit(pair[1]);
        }
        GitOid::new(algorithm, &bytes[..usize::from(algorithm.oid_len())])
            .expect("fixture OID has valid length")
    }

    fn hex_digit(value: u8) -> u8 {
        match value {
            b'0'..=b'9' => value - b'0',
            b'a'..=b'f' => value - b'a' + 10,
            _ => panic!("fixture OID is lower-case hexadecimal"),
        }
    }

    fn header_oid(data: &[u8], field: &[u8], algorithm: HashAlgorithm) -> GitOid {
        let header = data
            .split(|byte| *byte == b'\n')
            .take_while(|line| !line.is_empty());
        let value = header
            .into_iter()
            .find_map(|line| line.strip_prefix(field))
            .expect("fixture object contains expected header");
        oid_from_hex(algorithm, value)
    }

    fn tree_entry_oid(data: &[u8], wanted_name: &[u8], algorithm: HashAlgorithm) -> GitOid {
        let oid_length = usize::from(algorithm.oid_len());
        let mut remaining = data;
        while !remaining.is_empty() {
            let nul = remaining
                .iter()
                .position(|byte| *byte == 0)
                .expect("fixture tree entry has NUL");
            let header = &remaining[..nul];
            let space = header
                .iter()
                .position(|byte| *byte == b' ')
                .expect("fixture tree entry has mode/name separator");
            let name = &header[space + 1..];
            let oid_start = nul + 1;
            let oid_end = oid_start + oid_length;
            assert!(
                oid_end <= remaining.len(),
                "fixture tree entry includes an OID"
            );
            if name == wanted_name {
                return GitOid::new(algorithm, &remaining[oid_start..oid_end])
                    .expect("fixture tree OID has valid length");
            }
            remaining = &remaining[oid_end..];
        }
        panic!("fixture tree does not contain requested entry");
    }

    #[test]
    fn import_survives_source_removal_and_reloads_complete_snapshot_manifest() {
        let root = temporary_directory("end-to-end");
        let source = create_repository(&root);
        let store = root.join("store");
        fs::create_dir(&store).expect("create cold store directory");
        let chunk = store.join("0000000000000001.open");
        let repository = RepoId([0x41; 16]);

        let backend = SystemGitBackend::open(&source).expect("open fixture repository");
        let expected_objects = backend
            .reachable_objects(
                &backend
                    .snapshot_local_refs()
                    .expect("snapshot fixture refs")
                    .roots(),
            )
            .expect("read fixture object closure");
        let tag_oid = backend
            .resolve_revision("refs/tags/v1")
            .expect("resolve tag");
        let commit_oid = backend
            .resolve_revision("refs/heads/main")
            .expect("resolve branch commit");

        let mut writer = ChunkWriter::create(
            &chunk,
            ChunkHeader {
                generation: 7,
                chunk_id: 1,
                created_unix_secs: 0,
                flags: 0,
            },
        )
        .expect("create cold chunk");
        let mut catalog = InMemoryCatalog::default();
        let imported = import_local_refs(&backend, &mut writer, &mut catalog, repository, 7, 1)
            .expect("import local refs");
        assert_eq!(
            usize::try_from(imported.summary.objects_seen).expect("test count fits usize"),
            expected_objects.len()
        );
        assert_eq!(
            imported.summary.objects_written,
            imported.summary.objects_seen
        );
        assert_eq!(imported.summary.objects_deduplicated, 0);

        let mut manifest = SnapshotManifest::from_import(
            repository,
            RepoSnapshotId([0x42; REPO_SNAPSHOT_ID_LEN]),
            &imported,
            1_700_000_000,
            b"reflink-forest-import-test",
        )
        .expect("build complete snapshot manifest");
        manifest
            .add_optional_field(OptionalManifestField {
                tag: 0x8001,
                value: b"attestation retained verbatim".to_vec(),
            })
            .expect("add optional manifest field");
        let manifest_path = store.join("snapshot-v1");
        assert_eq!(
            publish_snapshot_manifest(&mut catalog, &manifest_path, &manifest)
                .expect("durably publish and expose snapshot manifest"),
            SnapshotPublicationStatus::Published
        );
        assert_eq!(
            catalog.repository_snapshot(repository, manifest.snapshot_id),
            Some(SnapshotVisibility::Ready)
        );
        drop(writer);

        fs::remove_dir_all(&source).expect("delete original Git repository");
        assert!(!source.exists());

        let reloaded =
            read_snapshot_manifest(&manifest_path).expect("reload durable snapshot manifest");
        assert_eq!(reloaded, manifest);
        let rewritten_manifest_path = store.join("snapshot-rewritten-v1");
        write_snapshot_manifest(&rewritten_manifest_path, &reloaded)
            .expect("rewrite manifest without losing optional fields");
        assert_eq!(
            read_snapshot_manifest(&rewritten_manifest_path).expect("reload rewritten manifest"),
            manifest
        );
        assert_eq!(
            verify_chunk(&chunk).expect("verify cold chunk after source removal"),
            6
        );

        // Every object needed by the captured refs still resolves through the
        // repo-scoped alias catalog and decodes from the cold chunk.
        for GitObject { oid, kind, data } in expected_objects {
            let record = record_for_oid(&chunk, &catalog, repository, oid);
            assert_eq!(record.kind, kind);
            assert_eq!(record.payload, data);
            assert_eq!(
                record.content_id,
                ContentId::for_object(kind, &record.payload)
            );
        }

        // Follow the retained tag to its commit, traverse the commit's root
        // tree and nested tree, and retrieve both required blobs with no Git
        // repository remaining on disk.
        let persisted_tag = reloaded
            .refs
            .iter()
            .find(|reference| reference.name == b"refs/tags/v1")
            .expect("tag stored in snapshot manifest");
        assert_eq!(persisted_tag.target, tag_oid);
        let tag = record_for_oid(&chunk, &catalog, repository, persisted_tag.target);
        assert_eq!(tag.kind, ObjectKind::Tag);
        assert_eq!(
            header_oid(&tag.payload, b"object ", reloaded.native_object_format),
            commit_oid
        );

        let commit = record_for_oid(&chunk, &catalog, repository, commit_oid);
        assert_eq!(commit.kind, ObjectKind::Commit);
        let root_tree_oid = header_oid(&commit.payload, b"tree ", reloaded.native_object_format);
        let root_tree = record_for_oid(&chunk, &catalog, repository, root_tree_oid);
        assert_eq!(root_tree.kind, ObjectKind::Tree);
        let top_blob_oid = tree_entry_oid(
            &root_tree.payload,
            b"top.txt",
            reloaded.native_object_format,
        );
        let directory_oid = tree_entry_oid(
            &root_tree.payload,
            b"directory",
            reloaded.native_object_format,
        );
        let top_blob = record_for_oid(&chunk, &catalog, repository, top_blob_oid);
        assert_eq!(top_blob.kind, ObjectKind::Blob);
        assert_eq!(top_blob.payload, b"top-level blob\n");
        let nested_tree = record_for_oid(&chunk, &catalog, repository, directory_oid);
        assert_eq!(nested_tree.kind, ObjectKind::Tree);
        let nested_blob_oid = tree_entry_oid(
            &nested_tree.payload,
            b"nested.txt",
            reloaded.native_object_format,
        );
        let nested_blob = record_for_oid(&chunk, &catalog, repository, nested_blob_oid);
        assert_eq!(nested_blob.kind, ObjectKind::Blob);
        assert_eq!(nested_blob.payload, b"nested blob\n");

        fs::remove_dir_all(&root).expect("remove temporary test directory");
    }

    fn minimal_manifest(repository: RepoId, snapshot_id: RepoSnapshotId) -> SnapshotManifest {
        SnapshotManifest {
            repository,
            snapshot_id,
            native_object_format: HashAlgorithm::Sha1,
            import_policy: ImportPolicy::LocalBranchesAndTags,
            refs: Vec::new(),
            summary: ImportSummary::default(),
            imported_unix_secs: 1_700_000_000,
            tool_version: b"reflink-forest-import-test".to_vec(),
            optional_fields: Vec::new(),
        }
    }

    #[test]
    fn interrupted_snapshot_publication_stays_incomplete_until_reconciled() {
        let root = temporary_directory("interrupted-publication");
        let repository = RepoId([0x51; 16]);
        let manifest = minimal_manifest(repository, RepoSnapshotId([0x52; REPO_SNAPSHOT_ID_LEN]));
        let path = root.join("snapshot-v1");
        let mut catalog = InMemoryCatalog::default();

        begin_snapshot_publication(&mut catalog, &manifest)
            .expect("record incomplete publication marker");
        write_snapshot_manifest(&path, &manifest).expect("durably write manifest");

        // Simulate a process stop after the durable file write and before the
        // Ready batch. Incomplete visibility is not a GC root.
        assert_eq!(
            catalog.repository_snapshot(repository, manifest.snapshot_id),
            Some(SnapshotVisibility::Incomplete)
        );
        assert!(catalog.gc_roots().expect("discover roots").is_empty());

        assert_eq!(
            reconcile_snapshot_publication(&mut catalog, &path)
                .expect("reconcile durable incomplete publication"),
            SnapshotPublicationStatus::Published
        );
        assert_eq!(
            catalog.repository_snapshot(repository, manifest.snapshot_id),
            Some(SnapshotVisibility::Ready)
        );

        fs::remove_dir_all(&root).expect("remove temporary test directory");
    }

    #[derive(Default)]
    struct FailSecondCatalogApply {
        inner: InMemoryCatalog,
        apply_count: usize,
    }

    impl Catalog for FailSecondCatalogApply {
        fn apply(
            &mut self,
            batch: reflink_forest_index::CatalogBatch,
        ) -> Result<(), reflink_forest_index::CatalogError> {
            self.apply_count += 1;
            if self.apply_count == 2 {
                return Err(reflink_forest_index::CatalogError::Backend(
                    "injected Ready publication failure".to_owned(),
                ));
            }
            self.inner.apply(batch)
        }

        fn object_location(&self, id: ContentId) -> Option<reflink_forest_index::ObjectLocation> {
            self.inner.object_location(id)
        }

        fn oid_alias(&self, repo: RepoId, oid: &GitOid) -> Option<ContentId> {
            self.inner.oid_alias(repo, oid)
        }

        fn repository_snapshot(
            &self,
            repository: RepoId,
            snapshot: RepoSnapshotId,
        ) -> Option<SnapshotVisibility> {
            self.inner.repository_snapshot(repository, snapshot)
        }

        fn chunk(
            &self,
            generation: u32,
            chunk_id: u64,
        ) -> Option<reflink_forest_index::ChunkMetadata> {
            self.inner.chunk(generation, chunk_id)
        }
    }

    #[test]
    fn failed_ready_catalog_commit_leaves_the_durable_snapshot_incomplete() {
        let root = temporary_directory("failed-ready-publication");
        let repository = RepoId([0x61; 16]);
        let manifest = minimal_manifest(repository, RepoSnapshotId([0x62; REPO_SNAPSHOT_ID_LEN]));
        let path = root.join("snapshot-v1");
        let mut catalog = FailSecondCatalogApply::default();

        assert!(matches!(
            publish_snapshot_manifest(&mut catalog, &path, &manifest),
            Err(SnapshotPublicationError::Catalog(
                reflink_forest_index::CatalogError::Backend(_)
            ))
        ));

        // The file is durable before the Ready catalog write is attempted,
        // and the failed atomic batch did not make the snapshot visible.
        assert_eq!(
            read_snapshot_manifest(&path).expect("read durable manifest"),
            manifest
        );
        assert_eq!(
            catalog
                .inner
                .repository_snapshot(repository, manifest.snapshot_id),
            Some(SnapshotVisibility::Incomplete)
        );
        assert!(catalog.inner.gc_roots().expect("discover roots").is_empty());

        fs::remove_dir_all(&root).expect("remove temporary test directory");
    }

    fn corpus_bytes(seed: u64, len: usize) -> Vec<u8> {
        let mut state = seed;
        (0..len)
            .map(|_| {
                state = state.wrapping_add(0x9e37_79b9_7f4a_7c15);
                let mut value = state;
                value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
                value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
                (value ^ (value >> 31)) as u8
            })
            .collect()
    }

    fn fixed_manifest_prefix() -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(SNAPSHOT_MANIFEST_MAGIC);
        put_u16(&mut bytes, SNAPSHOT_MANIFEST_VERSION);
        bytes.extend_from_slice(&[0; 16]); // repository
        bytes.extend_from_slice(&[0; REPO_SNAPSHOT_ID_LEN]);
        bytes.push(HashAlgorithm::Sha1.tag());
        bytes.push(import_policy_tag(ImportPolicy::LocalBranchesAndTags));
        put_u16(&mut bytes, 0);
        for _ in 0..5 {
            put_u64(&mut bytes, 0);
        }
        put_u16(&mut bytes, 0); // tool version
        bytes
    }

    #[test]
    fn untrusted_manifest_decoder_fuzz_corpus_is_total_and_count_bounded() {
        let lengths = [0, 1, 7, 8, 9, 63, 64, 127, 128, 255, 1024, 4096];
        for seed in 0..64 {
            for len in lengths {
                let bytes = corpus_bytes(seed, len);
                assert!(std::panic::catch_unwind(|| {
                    let _ = decode_snapshot_manifest(&bytes);
                })
                .is_ok());
            }
        }

        // Ref and extension counts are checked against the bytes remaining in
        // the bounded manifest before either collection reserves capacity.
        let mut impossible_refs = fixed_manifest_prefix();
        put_u32(&mut impossible_refs, u32::MAX);
        put_u32(&mut impossible_refs, 0);
        assert!(matches!(
            decode_snapshot_manifest(&impossible_refs),
            Err(SnapshotManifestError::Invalid(_))
        ));

        let mut impossible_extensions = fixed_manifest_prefix();
        put_u32(&mut impossible_extensions, 0);
        put_u32(&mut impossible_extensions, u32::MAX);
        assert!(matches!(
            decode_snapshot_manifest(&impossible_extensions),
            Err(SnapshotManifestError::Invalid(_))
        ));
    }
}
